version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
  db-migrate:
    image: kilna/liquibase-postgres:42.1.4
    environment:
      LIQUIBASE_DATABASE: postgres
      LIQUIBASE_USERNAME: postgres
      LIQUIBASE_PASSWORD: postgres
    volumes:
      - ./src/main/resources/database/changelog/:/workspace/
    entrypoint:  /workspace/migrate.sh
#    command: ["/bin/sh", "-c", "/bin/sh -i"]
