spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    platform: postgres
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
    jpa:
      database: POSTGRESQL